---
# Only uncomment line 3 if using older docker-compose not "docker compose"
#  version: "2.6"
# Open-vpn Docker compose file
# sudo docker pull openvpn/openvpn-as
services:
  openvpn-as:
    image: openvpn/openvpn-as:latest
    container_name: openvpn-as
#Network pre-recs
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - MKNOD
#Ports required
#943 = Web and admin gui
    ports:
      - 943:943
      - 443:443
      - 1194:1194/udp
    volumes:
      - ~/openvpn-data:/openvpn
    restart: unless-stopped
